- name: Launch instances
  gce:
    instance_names: "{{ base_instance_name }}"
    machine_type: "{{ machine_type }}"
    image: "{{ image_family }}"
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ project_id }}"
    disk_auto_delete: true
    zone: "us-east1-b"
    state: present
  register: gce

- name: Wait for SSH to come up
  wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
  loop: "{{ gce.instance_data }}"

- name: Add host to groupname
  add_host: hostname={{ item.public_ip }} groupname=new_instances
  loop: "{{ gce.instance_data }}"


#- name: Terminate instances
#  gce:
#    instance_names: "{{ base_instance_name }}"
#    machine_type: "{{ machine_type }}"
#    image: "{{ image_family }}"
#    service_account_email: "{{ service_account_email }}"
#    credentials_file: "{{ credentials_file }}"
#    project_id: "{{ project_id }}"
#    disk_auto_delete: true
#    zone: "us-east1-b"
#    state: absent
