---
- name: install some dependecies
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items:
    - git
    - default-libmysqlclient-dev
    - python-dev
    - python-pip
    - gunicorn
  tags: deploy


- name: deploy application
  git:
    repo: '{{ flask_app_source }}'
    dest: /opt/flask_app
    version: '{{ flask_app_version }}'
  tags: deploy

- name: install all pip packages
  pip:
    name: '{{ item }}'
    state: present
  with_items:
    - flask
    - flask-mysql
    - markupsafe
  tags: deploy


- name: create version file
  template:
    src: app-version.txt.j2
    dest: /tmp/app-version.txt
    owner: root
    group: root
    mode: 0644
  tags: deploy


- name: configure the database connection
  template:
    src: database.cfg.j2
    dest: /opt/flask_app/database.cfg
    owner: root
    group: root
    mode: 0644
  tags: deploy


- name: Copy flaskapp service file
  template:
    src: flaskapp.service.j2
    dest: /lib/systemd/system/flaskapp.service
  tags: deploy


- name: Start and enable flaskapp service
  systemd:
    name: flaskapp
    enabled: yes
    daemon_reload: yes
    state: restarted
  tags: deploy
