---
- name: install some dependecies
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - git
    - libmysqlclient-dev
    - python-dev
    - python-pip
    - gunicorn


- name: deploy application
  git:
    repo: '{{ flask_app_source }}'
    dest: /opt/flask_app
    version: '{{ flask_app_version }}'


- name: install all pip packages
  pip:
    name: '{{ item }}'
    state: present
  with_items:
    - flask
    - flask-mysql
    - markupsafe


- name: create version file
  template:
    src: app-version.txt.j2
    dest: /tmp/app-version.txt
    owner: root
    group: root
    mode: 0644


- name: configure the database connection
  template:
    src: database.cfg.j2
    dest: /opt/flask_app/database.cfg
    owner: root
    group: root
    mode: 0644


- name: start the application
  command: gunicorn --chdir /opt/flask_app --bind 0.0.0.0:8000 --daemon wsgi:app
