---
- name: Create instance template for flask app
  hosts: localhost
  gather_facts: no
  connection: local

  roles:
    - { name: gce_instance_template, provision: true }


- name: Deploy flask app
  hosts:
    - new_instances
  connection: ssh
  remote_user: point
  gather_facts: yes
  become: yes

  vars_files:
    - vars/db_secrets.yaml

  roles:
    - { name: flask_app }


- name: Create instance template for flask app
  hosts: localhost
  gather_facts: no
  connection: local

  roles:
    - { name: gce_instance_template, template: true }
